### ISSUE TITLE
Typescript Types

### ISSUE THREAD

**Issue by ivank** [BastienAr/stream-mock#18]
Awesome package!
Used it for some time, and figured I'd like some typescript types for it. It would be best if you could bundle some, but in the meantime I've added some as `@types/stream-mock` https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34398 Hope you don't mind :)

**Comment by BastienAr** [comment]
Hey, nice job ! Actually I have in my roadmap to rewrite this module in ts. Thanks this will be very useful   in the meantime.

**Comment by BastienAr** [comment]
Available in release [2.0.2](https://github.com/BastienAr/stream-mock/releases/tag/v2.0.2)
